### ISSUE TITLE
Uploading an existing AOI needs to treat data as new version?

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#18]
If a user uploads an existing AOI as a new AOI, it would currently fail. Another option would be to treat such an upload as an update to the existing AOI, and the data included in the uploaded .zip would be considered new versions, if different that the existing data.

**Comment by jkeifer** [comment]
My opinion of this idea is that it means that the API will not actually do what it says. I think that in this case the upload should fail early and with a reasonable error message signifying to the user that an AOI of that name already exists. If the user really wanted to update the existing AOI, they could just as easily use the update function.

Of course, merely saying that the update function exists doesn't explain how to do the diff of the new data to know what has changed. See issue #19  for this discussion.

**Comment by lbross** [comment]
I concur that the upload should fail if it is a duplicate. There is code in PC-BAGIS to prevent a user from trying to upload an existing AOI.

**Comment by jkeifer** [comment]
Currently, uploading an AOI with the same name as an existing AOI will fail, as will uploading one with the same ID. I am going to close this issue given that this is the desired behavior as discussed in this thread. If that changes please reopen.
