### ISSUE TITLE
Need to enable and configure URL parameter filtering

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#26]
The ability to filter results returned from API queries using arbitrary queries is highly necessary and desired. Currently, the only filtering is the AOI hierarchical query filtering defined by the URL structure. This does not allow arbitrary queries. It will also not help as more generic endpoints are created for each of the project models, per #24 .

The django rest framework supports URL-based query filters via the django-filter package. To use it, the backend needs to be enabled and filters need to be configured:

```
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',)
}
```

See http://www.django-rest-framework.org/api-guide/filtering/ for more information on filtering and what is needed to use django-filter and configuring the individual filters.

**Comment by jkeifer** [comment]
Here is a list of filters that I think are mostly global:
- name search
- date created range
- date modified range
- created by

Specific filters:
- Uploads/downloads should be filterable by expired/not expired.
- Uploads should possibly be filterable by status.

I am not certain of what else is likely useful as a filter. I am going to start with these and see how they go.

**Comment by jkeifer** [comment]
Filtering is setup on all main url endpoints that return a list of records. Some examples:
- Search icontains: `?search=<a_string>`
- Created at: `?created_at=2016-03-17T06:02:03.377000Z`
- Created after: `?created_after=2016-03-17T06:02:03.377000Z`
- Created before: `?created_before=2016-04-17T08:51:07.455987Z`
- Created range: `?created_after=2016-03-17T06:02:03.377000Z&?created_before=2016-04-17T08:51:07.455987Z`
- Created by: `?created_by=<username>` (this is an icontains search; if an exact search would also be desirable I can add that easily.)

Same can be done with `modified_at`/`modified_after`/`modified_before`. All parameters can be combined using `&`. More parameters are available; essentially all model fields have been parameterized, though most have not been tested and I am sure some won't work. However, if any are thought to be useful but not functioning or could be improved, please create an issue. Changes are not particularly difficult and can be added as needed.

**Comment by jkeifer** [comment]
One last note: I chose to use django-filter to implement this functionality as that was what was featured in the drf documentation. However, after getting this all running, I found a note about django-url-filter. If filtering becomes more needed and complex queries are desirable, this latter package seems to offer an easier means of building support for complex queries using what is essentially the django filtering syntax.

**Comment by lbross** [comment]
What is/are the wildcard(s) for icontains search?

**Comment by jkeifer** [comment]
Honestly, I am uncertain, and the docs are not particularly illuminating in this regard. I know a regex mode can be specified for complex search support obviously including wildcards, but that mode is not currently enabled.

I'd say we just need to test it; you can do that if you like, or I can do so when I have a chance (probably not today). If you find you want regex support I can enable it easily.

**Comment by lbross** [comment]
No problem. Let's hold off on any testing until we have some requirements.
