### ISSUE TITLE
Create endpoints to get all uploads/downloads for a given user

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#28]
Need easy-to-query endpoints to get upload and download transactions for a user, for use by the desktop client.

**Comment by jkeifer** [comment]
Actually, in thinking through this, the best solution is probably to always filter the results of the existing endpoints by user so a user can only see their own uploads/downloads. Then, it would probably be best to create new endpoints to list all the uploads/downloads, which are only accessible by admins.

**Comment by lbross** [comment]
@jdduh: Can you confirm the security requirements? I think we would want regular users to be able to see others' uploads, but perhaps this isn't right. I'm having trouble remembering why we asked for this in the first place unless it was to provide a filter where the user had the option of only seeing their own uploads.

**Comment by jkeifer** [comment]
Let me clarify, I do not mean AOIs. I mean the upload/download records themselves. Essentially, the upload/download history, not the AOIs/updates created from any uploads a user may have submitted.

In other words, Alice should be able to see Bob's AOIs, but not Bob's upload records. And Bob can see his own uploads, but not Alice's. He can see any AOIs Alice may have added, and he can see updates to his AOIs from uploads Alice has submitted.

**Comment by jdduh** [comment]
Agree with Jarrett's last comment. AOIs are visible to all. The logs are available only to individual users.

**Comment by lbross** [comment]
I'm trying to understand how we will use this endpoint. If you want to see the history of a stored AOI, I would think you'd want to see any changes regardless of who made it. I don't see much need to query for a record of what you alone have changed in the db. But maybe I'm missing something.

What information would be returned by this endpoint?

**Comment by jkeifer** [comment]
It's not for AOI history, but user history. So, sending a GET request to these endpoints would return all of the uploads/downloads a user has made, respectively.

I believe the idea here was that you were going to hit this endpoint to pull the records to show in the upload and download interfaces in the desktop client. Right now these endpoints exist, but are not filtered by the active user, so you see all users' activity.

**Comment by jdduh** [comment]
Ok, I change my mind. It seems individual users will need to see the complete upload log to know what had been done on the AOI. The download log is not important for regular users to know whoelse downloaded the AOI, but the administrators might be interested in knowing how many times the AOI was downloaded by whom. Is it possible to implement the log filter so that the filter is optional and more flexible (e.g., filter by date/time range or other attribute). Can users provide remarks/notes when uploading the AOIs?

**Comment by jkeifer** [comment]
Again, this is not a log of what has been done to the AOI. It is simply to return a list of upload records that pertain to a given user. That is, uploads that a given user has initiated. No regular user should ever want to see these records for other users, just themselves.

I do agree that admins might want to see a complete list that is not filtered by user, but that is why I proposed an additional endpoint that is admin-only.

Additionally, a comment field is included for uploads, but that is also intended to get passed onto whatever the base object was that was uploaded (a new AOI, an updated GDB, etc.).

**Comment by lbross** [comment]
At this time, there is no place on the PC-BAGIS interface to use this kind of information. I'm running late and will post an image later today. Essentially there is a top grid that lists all the AOIs in the db, a middle grid that lists the tasks currently running or completed during the current session, and some fields on the bottom to control uploading/downloading aois.

Just want to make sure Jarrett isn't working on something we won't use. Perhaps there is a plan to use this in the webapp?

**Comment by jkeifer** [comment]
Well, I was just going through the open tickets and saw this one, at which point I had the thought that kicked this all off. Implementing the filtering by user is literally one line, so if we can all agree on it I will do it. But I wasn't actually working on this, I just was writing down my thought for later.

As for where this will be used, we discussed needing this for the desktop client, though obviously that is need is for the future. And it would definitely be used by an online app once we are at the point of including such information.

**Comment by lbross** [comment]
I updated the [documentation on the google site](https://sites.google.com/site/nwccspatialservices/ebagis/database-tools/aoi-uploader-downloader/aoi-downloader-add-in) for the AOI Menu. I'm renaming it from AOI Downloader since it now includes both uploads and downloads. There is a screenshot of the current UI in the documentation.

The desktop client is AOI-centric thus far. I can forsee the user needing to filter AOI's when we get a lot in the database. But this would just be a query for all the AOI's that they uploaded. Or they may want to query all AOI's uploaded in a date range.

Does @jdduh want to add an AOI audit log generated by the server that can be viewed from the desktop? If so, we need to hammer out a spec both for server and client. Likely on a separate issue.

**Comment by jdduh** [comment]
For the desktop tool, please add a button (or URL) for users to view the log of individual AOIs.

**Comment by jkeifer** [comment]
Adding this in fit perfectly into what I was working on, so I did it. Actually, the filtering was already in place for non-admin user uploads, apparently, so I setup this filtering to be the default for all users and on downloads as well. So requests to `/api/rest/uploads` or `/api/rest/downloads` will only show the upload/download records for the current user.

Admins also have the option of including the url parameter show_all flag to true to show all uploads/downloads. For example, if logged in as an admin user, `/api/rest/uploads/?show_all` will show all uploads by all users. This can be combined with other url parameters such as the search/filtering implemented per #26, such as `/api/rest/uploads/?show_all&created_by=jkeifer` which will show all uploads by user jkeifer.

I don't think this new behavior should affect the desktop client at all, and it _will not_ filter the AOI records returned by `/api/rest/aois`.

I agree that AOIs should have a log available that shows all activity. However, such a thing is completely unrelated to this work and needs to be captured in a separate issue (see #54).

**Comment by jkeifer** [comment]
Forgot to mention, this change is deployed on the beta test instance.

**Comment by lbross** [comment]
What does this return? Just a list of the aoi id's? Or basic information about each aoi. In the future, it would be helpful if you could past the json payload as a comment on the issue so I know what I should expect when making a request. Thanks.

**Comment by jkeifer** [comment]
If you ever have a question about responses or the general structure of the API you can browse to the site in a web browser. The UI will allow you to navigate the API and you can see the responses in json format.

In any case, the response format has not changed; see below. Again, this feature is for the upload and download endpoints; it has nothing to do with AOI records. The list returned at each of these endpoints is simply filtered to provide only uploads or downloads that belong to the current user.

```
[
    {
        "id": "f0cf7b0a-391d-4a00-92cd-78dc040ac2a9",
        "url": "https://test.ebagis.geog.pdx.edu/api/rest/uploads/f0cf7b0a-391d-4a00-92cd-78dc040ac2a9/",
        "user": "https://test.ebagis.geog.pdx.edu/api/rest/users/2/",
        "task": {
            "id": 78,
            "result": {
                "exc_message": "[Error 183] Cannot create a file when that file already exists: u'D:\\\\projects\\\\ebagis\\\\testing\\\\ebagis_beta\\\\django-ebagis-site\\\\AOIs\\\\teton_map'",
                "exc_type": "WindowsError"
            },
            "task_id": "e2fe08ca-3949-4b26-93cd-1c7adc5c1ea3",
            "status": "FAILURE",
            "date_done": "2016-03-17T05:57:15.456000Z",
            "traceback": "Traceback (most recent call last):\n  File \"c:\\anaconda_x86\\envs\\ebagis_beta\\lib\\site-packages\\celery\\app\\trace.py\", line 240, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"c:\\anaconda_x86\\envs\\ebagis_beta\\lib\\site-packages\\celery\\app\\trace.py\", line 438, in __protected_call__\n    return self.run(*args, **kwargs)\n  File \"d:\\projects\\ebagis\\testing\\ebagis_beta\\django-ebagis\\ebagis\\tasks.py\", line 62, in process_upload\n    imported_obj = upload_class.create_from_upload(upload, temp_path)\n  File \"d:\\projects\\ebagis\\testing\\ebagis_beta\\django-ebagis\\ebagis\\models\\aoi.py\", line 100, in create_from_upload\n    def _parent_object(self):\n  File \"c:\\anaconda_x86\\envs\\ebagis_beta\\lib\\site-packages\\django\\utils\\decorators.py\", line 184, in inner\n    return func(*args, **kwargs)\n  File \"d:\\projects\\ebagis\\testing\\ebagis_beta\\django-ebagis\\ebagis\\models\\aoi.py\", line 216, in create\n  File \"d:\\projects\\ebagis\\testing\\ebagis_beta\\django-ebagis\\ebagis\\models\\mixins.py\", line 161, in path\n    \"\"\"On first run, creates the directory for a directory-using\nWindowsError: [Error 183] Cannot create a file when that file already exists: u'D:\\\\projects\\\\ebagis\\\\testing\\\\ebagis_beta\\\\django-ebagis-site\\\\AOIs\\\\teton_map'\n",
            "hidden": false,
            "meta": "eJxrYKotZIzgYGBgSM7IzEkpSs2LLdYDADylBhk="
        },
        "md5": "3d721d96846c9080df0214c8fb8788ec",
        "file": "https://test.ebagis.geog.pdx.edu/api/rest/uploads/D%3A/projects/ebagis/testing/ebagis_beta/django-ebagis-site/media/uploads/2016/03/16/f0cf7b0a-391d-4a00-92cd-78dc040ac2a9.part",
        "filename": "teton_map.zip",
        "offset": 31931004,
        "created_at": "2016-03-17T05:56:49.336000Z",
        "status": 2,
        "completed_at": "2016-03-17T05:56:52.626000Z",
        "object_id": "a65602d9-f8be-4ee1-89bc-e0018ddedfc2",
        "is_update": false,
        "parent_object_id": null,
        "comment": "",
        "content_type": 24,
        "parent_object_content_type": null
    }
]
```
