### ISSUE TITLE
Ignoring unused hru layers

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#3]
Issue references PSU-CSAR/vb-bagis-h#2:
- Need to ignore oldgrid, polygrid_v, and r00x layers
- Need to accommodate a _hru.gdb that has been filtered by the desktop bagis uploader
  - Check name of _hru.gdb with the enclosing HRU directory to make sure need to drop _ from name if exists (that is, if HRU is named _hru and the gdb is _hru.gdb, then the gdb should be named _hru. But if the HRU is named hru and the gdb is _hru.gdb, then the gdb should be named hru.).

**Comment by lbross** [comment]
Any estimate on how soon you'll get to this one? I would like to work this on the PC-BAGIS side but if you're not ready, it will temporarily end the ability of PC-BAGIS to upload.

**Comment by jkeifer** [comment]
I should have time to work on it tomorrow and Wednesday.

**Comment by jkeifer** [comment]
I have made these changes on a dev branch. I will test them tomorrow and if they work okay I will merge them into master and deploy them to the test instance for you.

**Comment by jkeifer** [comment]
As of commit 67092a8d8ba52dc362cbe13f60a2821599746d25 this has been finished and merged into master. The test instance of the site has been updated accordingly and I tested it without problems. If you experience any issues please feel free to make a new issue or reopen this one as is appropriate.
