### ISSUE TITLE
Unable to upload AOI with zones

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#31]
I get the following error when I try to upload an aoi containing a zones folder. My Python knowledge is limited but it looks like the issue may be the missing param.gdb. However, this is a valid use case as this folder won't be present if parameters haven't been generated for BAGIS-P.

"Traceback (most recent call last):   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\celery\app\trace.py", line 240, in trace_task     R = retval = fun(_args, *_kwargs)   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\celery\app\trace.py", line 438, in **protected_call**     return self.run(_args, *_kwargs)   File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\tasks.py", line 352, in add_aoi     comment=aoiupload.comment)   File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\tasks.py", line 335, in extract_and_import_aoi     comment=comment)   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner     return func(_args, *_kwargs)   File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\aoi.py", line 106, in create     aoi,   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner     return func(_args, *_kwargs)   File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\zones.py", line 136, in create     user)   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner     return func(_args, *_kwargs)   File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\zones.py", line 105, in create     user)   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner     return func(_args, *_kwargs)   File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\zones.py", line 71, in create     hruzonesdata_obj)   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner     return func(_args, *_kwargs)   File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\geodatabase.py", line 224, in create     gdb = arcpyGeodatabase.Open(geodatabase_path)   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\arcpy_extensions\geodatabase.py", line 84, in Open     cls.validate_geodatabase(path)   File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\arcpy_extensions\geodatabase.py", line 119, in validate_geodatabase     raise GeodatabaseError(e) GeodatabaseError: "c:\windows\temp\AOI_3stp9r\zones\my_elev\param.gdb" does not exist "

**Comment by jkeifer** [comment]
I thought HRUs always had param.gdbs. But I guess that is wrong; I'll make the the change with the current round of revisions I have been debugging.

**Comment by jkeifer** [comment]
Fixed in dev.

**Comment by lbross** [comment]
Just validated this fix by uploading an aoi with zones but no param.gdb and got the following error. Can you take a look?
Traceback (most recent call last):
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\celery\app\trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\celery\app\trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)
  File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\tasks.py", line 352, in add_aoi
    comment=aoiupload.comment)
  File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\tasks.py", line 335, in extract_and_import_aoi
    comment=comment)
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner
    return func(_args, *_kwargs)
  File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\aoi.py", line 106, in create
    aoi,
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner
    return func(_args, *_kwargs)
  File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\zones.py", line 136, in create
    user)
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner
    return func(_args, *_kwargs)
  File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\zones.py", line 105, in create
    user)
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner
    return func(_args, *_kwargs)
  File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\zones.py", line 71, in create
    hruzonesdata_obj)
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\django\utils\decorators.py", line 145, in inner
    return func(_args, *_kwargs)
  File "d:\projects\ebagis\testing\ebagis_test\django-ebagis\ebagis\models\geodatabase.py", line 224, in create
    gdb = arcpyGeodatabase.Open(geodatabase_path)
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\arcpy_extensions\geodatabase.py", line 84, in Open
    cls.validate_geodatabase(path)
  File "C:\Anaconda_x86\envs\ebagis_test\lib\site-packages\arcpy_extensions\geodatabase.py", line 119, in validate_geodatabase
    raise GeodatabaseError(e)
GeodatabaseError: "c:\windows\temp\AOI_m5eueq\zones\hru_ca\param.gdb" does not exist

**Comment by jkeifer** [comment]
That's because the fix is in the big round of changes I made, which has not been deployed to the current test instance. I am still waiting for the domain names to get setup so I can configure multiple sites in IIS and create a second "unstable" test instance.

**Comment by lbross** [comment]
Geoffrey ~

Can we get a status on the domain names being set-up for the test instance?
My guess is this won't be done before Jarrett flees the country. Thanks --
Lesley

**Comment by lbross** [comment]
Should this be fixed on https://ebagis.geog.pdx.edu/? Or is that server still running the old code? If so, is https://beta.ebagis.geog.pdx.edu/ running the new code? Do you recommend validating there? Or waiting until it is moved to stable test?

**Comment by jkeifer** [comment]
I don't remember if it is fixed on the stable test, but I know it is fixed on the beta test. I'd recommend testing always against the beta test unless it breaks.

Over time, as the beta is proven to be stable enough, it's changes will be migrated into the stable test. The idea of having the two is to ensure you have something to test against, even if it is not the most recent version, in case something breaks the beta test (like if a make an update and break something) and I am not able to get to fixing it right away.

**Comment by lbross** [comment]
Is there a 'testUser' in the database for beta test? If so, can you send me an e-mail with the password?  I will develop and test against beta test going forward unless it breaks.

**Comment by jkeifer** [comment]
It should be there and it should have the same password. If you experience any issues or do not have that password let me know. I don't have the password right in front of me at the moment but I can look it up.

**Comment by lbross** [comment]
Just tried to connect using curl and can't. But it looks like the problem is in DNS, not with the user account: 
curl: (6) Could not resolve host: beta.ebagis.geog.pdx.edu

Does this need to go to PSU I/T? 

My curl request:
curl -X POST --form username=username --form password=password https://beta.ebagis.geog.pdx.edu/api/rest/api-token-auth/

**Comment by jkeifer** [comment]
I apologize, that should be https://test.ebagis.geog.pdx.edu/api/rest/api-token-auth/, not beta.ebagis. That was my mistake.

**Comment by lbross** [comment]
I can now get a token in test, but that's about all I can do. I get errors when hitting the aois endpoint (https://test.ebagis.geog.pdx.edu/api/rest/aois/) and when trying to upload an aoi. The error logging is debug/verbose here so I can't readily see what the problem is. If the server logs don't show anything, let me know and I'll try to send something. Perhaps you can interpret ...

**Comment by jkeifer** [comment]
Yes, I see the problem and I think I know what it is. I should be able to fix it this evening.

**Comment by jkeifer** [comment]
My install script failed to create the database migrations that were necessary to initialize the database correctly. So essentially all the ebagis models were missing. I've created an issue for this in the django-ebagis-site repo. Not sure why I didn't catch this before, but so it goes.

I manually ran the migrations so the database should now be setup properly. Please let me know if you have any other issues; I'm sorry I haven't had more time to do testing myself with this new instance.

**Comment by lbross** [comment]
I am able to upload aoi's to the new instance but am having trouble processing the response from the aois endpoint: (https://test.ebagis.geog.pdx.edu/api/rest/aois/). It looks like the json payload has changed and the root element no longer has a key that I can parse. I'm not sure if .NET can work with this. Thought I'd check before banging my head against the wall to see if this is intentional?

new: 
[{
"url":"https://test.ebagis.geog.pdx.edu/api/rest/aois/b83d561e-001a-43ab-b322-c5e73028c8f8/",
"name":"aoi1_05222013",
"created_at":"2016-02-08T19:09:26.482000Z",
"created_by":{"url":"https://test.ebagis.geog.pdx.edu/api/rest/users/4/","usern
ame":"testUser"},
"comment":""},
{"url":"https://test.ebagis.geog.pdx.edu/api/rest/aois/d5708c09-346a-4d28-ae0d-7f650ca46c
57/","name":"north_aoi_1","created_at":"2016-02-08T21:35:58.680000Z","created_by":{"url":"https://test.ebagis.geog.pdx.e
du/api/rest/users/4/","username":"testUser"},"comment":""}]

old (note the key here is "results":
{"count":10,"next":null,"previous":null,"results":[{"url":"https://ebagis.geog.pdx.edu/api/rest/aois/eEDFF/","name":"new
_aoi","created_at":"2015-08-01T23:50:28Z","created_by":{"url":"https://ebagis.geog.pdx.edu/api/rest/users/2/","username"
:"jkeifer"},"comment":"Test comment"},{"url":"https://ebagis.geog.pdx.edu/api/rest/aois/VNZpi/","name":"new_aoi2","creat
ed_at":"2015-08-01T23:52:47.795000Z","created_by":{"url":"https://ebagis.geog.pdx.edu/api/rest/users/2/","username":"jke
ifer"},"comment":"Test comment"},{"url":"https://ebagis.geog.pdx.edu/api/rest/aois/s1P05/","name":"aoi1_05222013","creat
ed_at":"2015-08-07T17:31:08.002000Z","created_by":{"url":"https://ebagis.geog.pdx.edu/api/rest/users/4/","username":"tes ...

**Comment by lbross** [comment]
I found a way to parse JSON arrays so this is no longer as urgent. I've updated the .NET code so it can parse either way.

**Comment by jkeifer** [comment]
I am going to close this issue and open a new one for paginating the API responses for all list endpoints.
