### ISSUE TITLE
Need to accommodate polygon_v layer in HRUs

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#32]
Non-contiguous HRUs use a layer named polygon_v rather than grid_v. The importer needs to accommodate the presence of this layer.

**Comment by jdduh** [comment]
Non-contiguous HRUs use a layer named polygon_v in addition to grid_v.

**Comment by jkeifer** [comment]
@jdduh It seems that this layer is supposed to be polygrid_v per PSU-CSAR/vb-bagis-h#17, not polygon_v. I am not sure where the polygon came from--perhaps it was just me--but can I get confirmation that it should in fact be polygrid?

**Comment by jkeifer** [comment]
I closed this with my commit as I successfully tested support for polygrid_v layers. If this is incorrect and it should really be polygon_v, please reopen.

**Comment by jdduh** [comment]
polygrid_v is the correct layer, not polygon_v. Sorry for the mix-up.
