### ISSUE TITLE
Celery task result should be filtered if status is STARTED

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#42]
With the new STARTED state for celery tasks, results shows as something like the following during processing:

```
    "result": {
        "hostname": "celery@basins",
        "pid": 9912
    },
```

I believe that is not desirable, and should be a result value filtered out when the state is STARTED. A result of None seem more appropriate.

**Comment by lbross** [comment]
What REST endpoint generates this response?

**Comment by jkeifer** [comment]
The upload and download object endpoints have this.  Here is an "example" (I edited a completed task to look like one that is STARTED):

```
{
    "id": "0dfdf168-ad7b-47b0-b7a8-5923d6f0507c",
    "url": "https://test.ebagis.geog.pdx.edu/api/rest/uploads/0dfdf168-ad7b-47b0-b7a8-5923d6f0507c/",
    "user": "https://test.ebagis.geog.pdx.edu/api/rest/users/2/",
    "task": {
        "id": 8,
        "result": {
            "hostname": "celery@basins",
            "pid": 9912
        },
        "task_id": "26264928-1343-4118-956c-15a714a17101",
        "status": "STARTED",
        "date_done": "2016-02-16T01:24:29.186000Z",
        "traceback": null,
        "hidden": false,
        "meta": "eJxrYKotZIzgYGBgSM7IzEkpSs2LLdYDADylBhk="
    },
    "md5": "3d721d96846c9080df0214c8fb8788ec",
    "file": "https://test.ebagis.geog.pdx.edu/api/rest/uploads/D%3A/projects/ebagis/testing/ebagis_beta/django-ebagis-site/media/uploads/2016/02/15/0dfdf168-ad7b-47b0-b7a8-5923d6f0507c.part",
    "filename": "maps_after_restart",
    "offset": 31931004,
    "created_at": "2016-02-16T01:22:27.032000Z",
    "status": 2,
    "completed_at": "2016-02-16T01:22:32.263000Z",
    "object_id": "35922216-7505-4e5f-91a5-4c3dec9fd8cc",
    "is_update": false,
    "parent_object_id": null,
    "comment": "",
    "content_type": 24,
    "parent_object_content_type": null
},
```

I think having a null result makes much more sense and may also mitigate a possible security problem (handing out the PID and other information is possibly harmless, but still makes me a bit uncomfortable if it isn't necessary.)

**Comment by lbross** [comment]
Thanks for showing the example with the complete payload. I wasn't using the result property in this context so this won't effect PC-BAGIS.

**Comment by jkeifer** [comment]
I didn't expect so, else you would have mentioned it when it changed. Even so, glad it won't impact you.
