### ISSUE TITLE
AOI downloads missing param.gdb folder

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#45]
In animas_AOI_prms and animas_AOI_prms_1 there should be a param.gdb geodatabase under the zones/hru_prms folder. I have confirmed that this geodatabase and its contents are in the zip file that is uploaded to the server. When I download the AOI, this geodatabase is missing. We had an earlier problem where we couldn't upload an AOI that was missing the param.gdb (issue #31) but now we seem to have the opposite problem.

**Comment by jkeifer** [comment]
I need some automated tests...

I should be able to dig into this tonight and I imagine it will be an easy fix. Sorry of the regression.

**Comment by lbross** [comment]
Actually we can close it. I just downloaded animas_AOI_prms_1 and it was there. Not sure what happened with animas_AOI_prms but I think we're fine.
