### ISSUE TITLE
auth tokens should expire

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#47]
Tokens are currently used for the REST API user authentication. However, the default token class provided by drf does not expire, so that leaves a gaping security hole: if a token is intercepted or otherwise compromised, an attacker has unending access to the site with the permissions of the compromised user.

Rather than leaving this hole open indefinitely, I think it best to make the tokens expire. Thus, an attacker only has access for a limited time. When a user's token expires, that user's username and password are required to generate a new token.

Currently the API endpoint to request a token is /api/rest/api-token-auth. However, this does not seem to me to be a good endpoint name. Therefore, to go along with this work, the endpoint should be updated to just /api/rest/token.

(Note: this work is already complete, I am just making this ticket for documentation and testing).

**Comment by jkeifer** [comment]
The work implementing these changes was done in commits 2c1d5c1f1d0b21c9fd52b71e85dc87dc581ff46c and 775bcf5d2980330c620d1c3e60318ed4162b9988 on the dev branch.

Tokens are currently set to expire weekly, as this seemed a good balance between security and annoyance (as users have enter their username/password when the token expires)

@lbross Lesley, I have switched the beta test instance to use the latest code committed to the dev branch, which includes this change. You will need to update your code to hit the /api/rest/token endpoint, rather than the /api/rest/api-token-auth endpoint.

Along with this new token stuff comes a few other large changes, such as using IDs rather than names for directories and files on disk (enables the ability to rename files, etc. in the database without having to change filenames or pointers to files). Please don't hesitate to let me know if you encounter any problems. I'll be the first to admit my testing is far from exhaustive, unfortunately.

If you do not have any issues with the tokens please close this issue or otherwise let me know.

**Comment by jkeifer** [comment]
@lbross I figured I should also mention: the nature of the changes, namely the change to using UUIDs for filenames in the file system, completely broke the old data model in a way that was not migrate-able. At least not for a reasonable amount of effort. So I had to wipe all AOI, upload, and download records in the database.

**Comment by lbross** [comment]
This is strange. I have my old token cached. When I validate against the validate url, it tells me the token is valid. When I try to use it to list the aois, it tells me it is invalid. Token is likely invalid given the changes but I don't know why the validate url isn't rejecting it. Sending curl requests in private e-mail so token isn't posted on GitHub :-)

**Comment by jkeifer** [comment]
I didn't test that endpoint and missed something vital to making it work correctly with the new tokens. Please give it another try, I made a quick fix that I think will correct the problem.

**Comment by lbross** [comment]
So far, so good. Closing.
