### ISSUE TITLE
Serve desktop settings and layer file for desktop users

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#49]
The desktop bagis currently bundles a json file and a lyr file, which are used for default parameters and display (if I understand correctly). However, updates to these files require a new bagis release. It would be optimal if these files could be downloaded periodically so that the desktop client can be updated without creating a new release.

To provide such functionality, we need to create two endpoints, one for the settings in json format, and the other to serve the lyr file.

I think the best way to allow updates to the settings and lyr file is to put them in a known, default location on the server (C:\ebagis). The settings file should be in yaml format, for ease of use. Updates to either will automatically be served when the client makes a new request.

**Comment by jkeifer** [comment]
@lbross You can get the desktop settings json by sending a GET request to /api/rest/desktop/settings/. 

The lyr file is available for download at /api/rest/desktop/lyr/.

If the implementation for these two works for you please close this issue or otherwise let me know.

**Comment by lbross** [comment]
@jkeifer Will get to this soon. Could we also get some documentation on how to update the lyr file and the values in the json response? Would be helpful to be able to update this without bugging you. Ultimately this should be on the google site but we can work with whatever format is easiest for you.

**Comment by jkeifer** [comment]
It's super easy. Under C:\ebagis is a file called desktop_settings.yaml and the BAGIS_Reference_Maps.lyr file. For settings updates just edit the .yaml file, and for lyr updates just replace the .lyr file. No other changes/restarts/etc. should be required to serve the new values/file.

**Comment by lbross** [comment]
It appears that these web services are secured. I'm not sure if they should be secured or not. @jdduh ? I have not built ebagis security into BAGIS v3 since all the ArcGIS services it is accessing are unsecured. How difficult would it be to treat these 2 services differently and have them NOT be secured?

**Comment by jkeifer** [comment]
You're right, I didn't explicitly make them unsecured as we had discussed. Sorry for that oversight. I believe that should be a simple fix, which I will try to deploy this evening.

**Comment by jdduh** [comment]
It's OK to allow unsecured web services for BAGIS V3.

**Comment by jkeifer** [comment]
I have updated those endpoints so they do not require any login or other type of authentication.

Was the above documentation on how to update the responses of these endpoints sufficient for the time being? Are there any other outstanding issues related to these endpoints?

**Comment by lbross** [comment]
Closing; These services are now integrated into BAGIS v3 and documented [here](https://sites.google.com/site/nwccspatialservices/ebagis/bagis-v3).
