### ISSUE TITLE
Can we update the token endpoint to return the user name and role along with the token?

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#58]
If we start allowing admins to delete AOI's it would be nice for the PC client to know if the user is an admin so it does not present a GUI with an invalid option. As long as a change is being made to the api, can we add the username as well? I have the user name because I am passing it in to ask for the token but my code can be more efficient if it comes from the server.

Could we also add role to the validate-token endpoint? I will cache it when I originally receive the token but it would be safer to update it when I check for a valid token in case it has changed.

**Comment by jkeifer** [comment]
I'm thinking through how this all will fit with the new account API endpoints. I will likely end up telling you to query different urls for these resources, but I want to make sure I fully think through the best way to do what you want and make it logically organized within the API structure.

So my answer is yes, but stay tuned for more details.

**Comment by jkeifer** [comment]
@lbross Here is the how I'm handling all this with the web UI:
- `api/rest/account/login`: `POST` to get a token for a given username and password
  
  To use this I think you should only have to:
  - update the endpoint you're hitting from the current `api/rest/token` endpoint
  - change the data value you are looking for from `token` to `key`. 
  
  I believe the request format should be the same. Please let me know if you have any issues.
- `api/rest/account/user`: `GET` the currently logged-in user based on the auth token in the request header
  
  This will return the following JSON data:
  
  ```
  {username: "username",
  email: "email@example.com",
  first_name: "first",
  last_name: "last",
  roles: ["ROLE_ADMIN", "ROLE_STAFF"],
  }
  ```
  
  Each role will only be returned if the respective property is set on the use providing that permission set.
  
  With this, the `validate_token` endpoint is essentially pointless. I have added an additional warning message stating as such to it's response. Please migrate to the new endpoint and let me know once you have so I can remove the old one. Same goes for the token endpoint, though I did not add a deprecation message to it.

You also asked about the token endpoint return the user info, but doing so would require some custom stuff that would be a bit messy with the new way I am handling all these bits. Instead, I would propose you make two requests: one for the token, then a second immediately after for the user. This is how I'm handling it with the web UI, and I've found it to work well. Please let me know if that would work for you.

Note that these changes are all active in the test instance on basins.

**Comment by lbross** [comment]
Just an FYI that all the endpoints need to have a trailing slash on them, for example: api/rest/account/login/. Otherwise the server throws an error :-(

**Comment by lbross** [comment]
Work is complete on PC-BAGIS to handle these API changes. Please let me know when code is migrated to the "prod" instance on basins and I'll post a new version of the add-in.

**Comment by jkeifer** [comment]
@lbross can this issue be resolved?

Also, just a note on the trailing slash: when I was using angular for the frontend, the way its router worked meant that it would eat any requests that did not end in a trailing slash. Now that django is in charge of routing for the frontend, its trailing-slash-append-redirect works again. If you omit the trailing slash, django will add it on to complete the request.

**Comment by lbross** [comment]
FYI ... it appears the API has been updated and the roles now appear in a different array called 'groups'. I will update PC-BAGIS to work with this.

@jkeifer: This is an array which means we can support > 1 group. Is your intention to allow multiple groups per user and the highest permission wins? Or will we only have 1 group per user in practice? I can support either but should clarify.

**Comment by lbross** [comment]
Handling security questions under issue #79
