### ISSUE TITLE
Unable to upload an aoi to test.ebagis

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#62]
Tried to upload a test aoi that has worked before and it no longer works. I am getting the attached error. It's possible something changed on my end because I'd been trying to get the chunked upload to work but I thought I reverted to my previous code. Can you check?
![typeerror](https://cloud.githubusercontent.com/assets/11527966/18457279/2d9e07ec-790c-11e6-977c-fca5e1bcee6f.png)

**Comment by lbross** [comment]
Just got the same error through curl using this url:
curl https://test.ebagis.geog.pdx.edu/api/rest/aois/ -H 'Authorization: Token 27d62e4fdcbcaf86f85b783cab6af7bce9138755' -X POST --form "file=@C:\Docs\Lesley\aoi1_09122016_1.zip" --form filename=aoi1_09122016_1 --form md5=c1be4f8824b9bdd736d559b971922eff

**Comment by jkeifer** [comment]
@lbross This is definitely on my end. I was hoping to take a look at it last night be did not have a chance. I will do so this evening for sure.

**Comment by jkeifer** [comment]
@lbross This was a simple error on my end that I missed after a dependency upgrade. Sorry for the inconvenience.

**Comment by lbross** [comment]
I confirm that uploads are working again. Thanks!
