### ISSUE TITLE
Menu updates

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/django-ebagis#65]
Please add a "Requests" menu item to show "Upload Requests" and "Download Requests" sub-menu items. The menu items are the same as the ones shown on the Hello sub-menu.
 
![image](https://user-images.githubusercontent.com/11510708/29754371-878e2bb2-8b38-11e7-8e09-78da78ddf3a0.png)

Please add a sub-menu item in the PRISM Statistics to show this menu item is "Under construction"

**Comment by jdduh** [comment]
Do users need to refresh the page to update the request status or the upload/download queue page refreshes themselves? If users do need to manually refresh the page, then please add the refresh instructions on the page.

**Comment by jkeifer** [comment]
We will add a dropdown menu on the right-hand side to the left of the user menu if users are logged in, which will have the links to the request pages.

As to refreshing the requests pages, I think we should have a refresh button the page. Today it will simply do the same as a browser refresh, but in the future it could do an ajax call to update the data in place, and we could have that automated every 30 seconds or something to poll for updates without user interaction.
