### ISSUE TITLE
About

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/django-ebagis#66]
Use the following text for the "Project Contributors" section. Feel free to edit whatever you think is appropriate.

Primary investigator and main contact: Geoffrey Duh (jduh@pdx.edu), Geography, Portland State University
System architect and programmer: Jarrett Keifer, [enter your contact and affiliation information here, if you prefer]
Webpage programmer: Aida Keifer, [enter your contact and affiliation information here, if you prefer]
ArcGIS Desktop add-in programmer: Lesley Bross, Geography, Portland State University

**Comment by jkeifer** [comment]
My preferred tagline:

System architect and programmer: Jarrett Keifer (github.com/jkeifer), Geography, Portland State University

**Comment by jdduh** [comment]
Looks good. Please come up with something for Aida so that the format is consistent for everyone. If she also wants to be "affiliated" with PSU Geography, then we can use something like:

Geography, Portland State University
Primary investigator and main contact: Geoffrey Duh (jduh@pdx.edu)
System architect and programmer: Jarrett Keifer (github.com/jkeifer)
Webpage programmer: Aida Keifer (email/contact)
ArcGIS Desktop add-in programmer: Lesley Bross (lbross@pdx.edu)
