### ISSUE TITLE
Celery tasks need to be abortable

### ISSUE THREAD

**Issue by jkeifer** [PSU-CSAR/django-ebagis#8]
As mentioned in PSU-CSAR/vb-bagis-h#8, tasks should have a method that can be used to abort/cancel them at any point before they complete.

See the following for more information:
http://celery.readthedocs.org/en/latest/userguide/tasks.html#custom-states
http://stackoverflow.com/a/25561389
http://celery.readthedocs.org/en/latest/userguide/workers.html#revoke-revoking-tasks

**Comment by jkeifer** [comment]
Also see http://docs.celeryproject.org/en/latest/reference/celery.contrib.abortable.html

This seems to be the easy way to implement cancellation for running tasks. I will need to ensure that the tasks we need to abort (just upload right now?) use this class a base class, and are regularly checking if the task has been aborted. 

Because each model has it's own create method, perhaps a good way to handle this is with multiprocessing: set the parent process in a sleep-check loop after spawning a child process to do the actual import processing. However, one disadvantage is that we need to ensure we check for the abort right before exiting any transactions to ensure proper rollback...

So perhaps better would be to check just before the exit of every transaction? Is there an easy, non-repetitive way to add those checks?

**Comment by jkeifer** [comment]
Interesting tidbit of information: https://github.com/celery/celery/issues/2335

Considering the issues I'm having with this, I may consider an approach that does not make use of the abortable task class.

**Comment by jkeifer** [comment]
This took an inordinate amount of time to complete due to the restrictions presented by celery. I am increasingly growing weary of celery, though I am certain I could not create a better alternative in a reasonable time frame.

In any case, I have impressed myself with the elegant solutions I have devised to get around celery's limitations. See `utils.transaction.py` for the result.

Based on the info in the link above, I knew tracking STARTED was messing with aborts via the abortable task class, so I created a way to wrap task functions in the abort check then setting the state to STARTED manually. I know this is a small race condition, but I don't imagine it to have a significant effect in practice (nonetheless, the race condition is there, so be aware it made need a little optimization if it does become a problem).

I also wrapped the task function in an exception handler to show the task status as SUCCESS with the message "Task Aborted". I felt this was better than letting the exception through and having the task as FAILED, even though it did what it should have.

Lastly, I added a new ABORTED state to the upload class (int value 4), to show that the upload itself is aborted.

Per #40, simply POST to /api/rest/uploads/<upload_id>/cancel to cancel the upload. Note, any authenticated user can currently cancel any task for which they know the ID, so I will be restricting this endpoint to only the user who created the upload or an admin, but that is tracked in #52.

**Comment by jkeifer** [comment]
@lbross The new code with this cancel endpoint is now live on the beta test site. Please let me know if/when you run into issue or if you have any questions.

**Comment by lbross** [comment]
I have this working. The only caveat I would add is that you have to explicitly set the request length to 0 or you will get a 411 error from the server. Nice job!

**Comment by jkeifer** [comment]
That's interesting. For testing I just used cURL to POST to the endpoint. I imagine it automatically sets the request length for me.

Is that it requires the request length such an issue that I should do some research about this now or I should worry about it later? Or should I not worry about it at all because it isn't really a problem, just an observation?

**Comment by lbross** [comment]
This is more an observation and guidance to any future developers who may use this endpoint. According to what I read, this is inherent with using a POST request.

**Comment by jkeifer** [comment]
Ahh, okay. In that case, it sounds like everything works on your end and I can close this out. Please feel free to reopen or make a new issue with a specific problem if needed.

Thanks!

**Comment by jkeifer** [comment]
Note that I did some more testing of the cancel function, this time to test.ebagis.geog.pdx.edu, not my dev instance. I found that I now needed to explicitly include the request length of 0 or I too got the 411.

Therefore, it seems to be an IIS requirement. For what I could tell, that requirement is also not to spec--the content length should not be required for POSTs with no content. But oh well.
