### ISSUE TITLE
Structure of download .zip file

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#88]
When I download an AOI and unzip the file, the top-level file is a folder with the same name as the AOI. The required .gdb's are inside this folder. I'm 95% sure this has changed. In earlier versions the .gdbs were at the root of the .zip file. This is confusing to the user because if you try to use the downloaded AOI in PC-BAGIS by opening up the top-level folder, it won't work. I am seeing the same behavior on test and production instances.

**Comment by lbross** [comment]
I think I can work around this by changing the code that extracts the AOI from the .zip file, if this is the structure we are going to use going forward. Please let me know.

**Comment by jkeifer** [comment]
@lbross You are correct, this was a change, per issue #69 . If you can easily work around it on your end I think that would be best.

**Comment by lbross** [comment]
Modified VB .NET code that extracts the files from the .zip to accommodate this change. Closing.
